watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"

    alignment:
      position: "top"
      center: false

    animation:
      enabled: true
      duration: 1000

    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "#8dbcff"

    window_flags:
      always_on_top: true
      windows_app_bar: true

    dimensions:
      width: "100%"
      height: 26

    padding:
      top: 3
      left: 3
      bottom: 0
      right: 3

    widgets:
      left:
        - "custom_button"
        - "pomodoro"
        - "wallpapers"
        - "active_window"

      center:
        - "clock"
      right:
        - "cava"
        - "volume"
        - "battery"
        - "cpu"
        - "power_menu"

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[app_name]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]} {win[app_name]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 30
      max_length_ellipsis: "..."
      monitor_exclusive: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M:%S}"
      label_alt: "{%I:%M:%S}"
      timezones: []
      callbacks:
        on_left: "toggle_calendar"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "󰄛"
      uptime: True
      blur: True
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Khel Khatam"]
        restart: ["\uead2", "ek aur baar"]
        signout: ["\udb80\udf43", "Dip out"]
        lock: ["󰌾", "lock"]
        sleep: ["\u23fe", "NiNi"]
        cancel: ["", "Nah!Im Good"]

  custom_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "󰣇"
      label_alt: "󰣇"
      class_name: "start-menu"
      callbacks:
        on_left: "exec start_menu"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | {power}W | {time_remaining}"
      update_interval: 5000
      time_remaining_natural: False
      hide_unsupported: True

      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 500

      status_thresholds:
        critical: 15
        low: 35
        medium: 70
        high: 90
        full: 100

      status_icons:
        icon_charging: "󱥸"
        icon_critical: "󰪞"
        icon_low: "󰪟"
        icon_medium: "󰪣"
        icon_high: "󰪤"
        icon_full: "󰪥"

      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "", launch: "cmd /c Taskmgr" }

  apps0:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "\uf489", launch: "wt" }
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 0
      gradient: 1
      foreground: "#e8600a"
      gradient_color_1: '#b84800'
      gradient_color_2: '#ff8c2a'
      gradient_color_3: '#c8960a'
      bars_number: 12
      bar_spacing: 2
      bar_width: 3
      bar_type: "bars"
      framerate: 65
      hide_empty: true
      noise_reduction: 32
      lower_cutoff_freq: 30
      higher_cutoff_freq: 16000
      output_bit_format: "8bit"
      sensitivity: 95
  wallpapers:
      type: "yasb.wallpapers.WallpapersWidget"
      options:
        label: "<span>\udb83\ude09</span>"
        image_path: # add the path of folder with wallpapers
        change_automatically: True # Automatically change wallpaper
        update_interval: 600 # If change_automatically is true, update interval in seconds
        gallery:
            enabled: true
            blur: true
            image_width: 220
            image_per_page: 8
            show_buttons: true
            orientation: "portrait"
            image_spacing: 12
            lazy_load: true
            lazy_load_delay: 80
            lazy_load_fadein: 400
            image_corner_radius: 16
            enable_cache: true
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[freq][current]} MHz"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"
        on_right: "toggle_menu"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      menu:
        enabled: true
        show_graph: true
        show_graph_grid: true
        graph_history_size: 60
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 110
      break_duration: 10
      long_break_duration: 20
      long_break_interval: 2
      auto_start_breaks: true
      auto_start_work: false
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 4
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#1e1e2e"
        circle_work_progress_color: "#a6e3a1"
        circle_break_progress_color: "#89b4a"
        circle_thickness: 10
        circle_size: 150
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "#000000"
        radius: 3
        offset: [ 1, 1 ]  

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]


                               
  